---
title: Biography
author: Ayman Amin
date: '2019-06-12'
summary: My Biography
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 3
---


# General Background

I am an **Associate Professor of Statistics** (since October 2020) at <a href = "http://www.menofia.edu.eg/Home/en">Faculty of Commerce, Menoufia University, Egypt</a>. Before that, I worked as an Assistant Professor of Statistics from September 2015 to September 2020 at <a href = "http://www.menofia.edu.eg/Home/en">Faculty of Commerce, Menoufia University, Egypt</a>. In addition, I worked as a Tutor for Statistics and Mathematics from February 2012 to June 2014 at <a href = "http://www.swin.edu.au/">Faculty of Science, Engineering and Technology, Swinburne University of Technology, Australia</a>. Moreover, I worked as a Teaching Assistant for Statistics and Mathematics from May 2007 to April 2010 at <a href = "http://www.menofia.edu.eg/Home/en">Faculty of Commerce, Menoufia University, Egypt</a>. I was awarded my PhD degree from <a href = "http://www.swin.edu.au/">Faculty of Science, Engineering and Technology, Swinburne University of Technology, Australia</a> (in January 2014). I received my MSC in Statistics (with excellent degree in October 2009) and BSC in Statistics and Social Science Computing (with excellent degree in June 2006) from <a href = "http://www.feps.eun.eg/">Faculty of Economics and Political Science (FEPS), Cairo University</a>, Egypt.

My research work is mainly in time series analysis and forecasting methods. In my *Master study*, I  proposed a Bayesian inference for multiplicative seasonal ARMA models by implementing MCMC Gibbs sampling algorithm. In addition in my *PhD study*, I continued my work in time series analysis but mostly in the real application of time series forecasting. In particular, I was working on proposing an automated statistical approach to forecasting Quality attributes of software systems. These Quality attributes include performance, reliability, and availability. This forecasting approach is mainly based on linear and non-linear time series models and wavelet analysis. Currently, I am mainly working on modeling *multiple seasonalities* aiming to propose a new efficient forecasting method that can be effectively applied in different research fields such as finance, economics and software engineering. 

I deliver statistical consultations for many clients such as regional projects, companies, and postgraduate students in different fields including information technology, social and educational sciences, linguistics, and medicine that require the statistical analysis and data mining as a main component in their work. 



# My Education History

## **PhD in Applied Statistics and Information Technology** 

**[April 2010 - January 2014], Faculty of Science, Engineering, and Technology (FSET), Swinburne University of Technology, Australia**.  

**Thesis Topic:** Automated Statistical Forecasting for Quality Attributes of Web Services


**Supervisor:**   Prof. Lars Grunske and Dr. Alan Colman

**Area of Study:** Quantitative Analysis for Quality Attributes of Software Systems

**Thesis Abstract:** This study proposes a collection of automated forecasting approaches for quality of service (QoS) attributes of Web services. Each one of these approaches is able to fit and forecast a specific type of QoS stochastic characteristics, however, taken together they will be able to fit different dynamic behaviors of QoS attributes and forecast their future values. In particular, the thesis proposes an automated forecasting approach for nonlinearly dependent QoS attributes, two automated forecasting approaches for linearly dependent QoS attributes with volatility clustering, and two automated forecasting approaches for nonlinearly dependent QoS attributes with volatility clustering. The accuracy and performance of the proposed forecasting approaches are evaluated and compared to those of the baseline ARIMA time series models using real-world QoS datasets of Web services characterized by nonlinearity and volatility clustering. The evaluation results show that each one of the proposed forecasting approaches outperforms the baseline ARIMA models. 



## **MSc in Statistics** 

**[with excellent degree, October 2006 - October 2009], Faculty of Economics and Political Science (FEPS), Cairo University, Egypt**.  

**Thesis Topic:** Bayesian Inference for Seasonal ARMA Models: A Gibbs Sampling Approach


**Supervisor:**   Prof. Mohamed Ismail and Prof. Emad Soliman

**Area of Study:** Bayesian Time Series Analysis

**Thesis Abstract:** This study develops a Bayesian inference for multiplicative seasonal ARMA model by implementing a fast, easy and accurate MCMC Gibbs sampling algorithm. The proposed algorithm does not involve any Metropolis-Hastings generation but is generated from normal and inverse gamma distributions. The proposed algorithm is illustrated using simulated examples and real datasets. 


## **Pre-MSc in Statistics** 

**[MSc Preparatory Year, September 2006 - July 2007], FEPS, Cairo University, Egypt**.  

**Main courses** of this year include:

- Theory of Statistics        
- Time Series Analysis (Classical and Bayesian)  
- Advanced Mathematics   
- Robust Regression Diagnostics 
- Advanced Econometrics 
- Biostatistics and Demography 

**Grade** is Very Good (and the First among the class students)


## **BSc in Statistics and Social Science Computing** 

**[with excellent degree, September 2002 - July 2006], FEPS, Cairo University, Egypt**.  


**Major Specialization** is Statistics and **Minor Specialization** is Social Science Computing.



# Awards

## SIG Travel Grant for the students/researchers, ACM

WOSP/SIPEW International Conference on Performance Engineering Support Travel Grant (ICPE, 2012), which is the SIG Travel Grant for the students/researchers from [Association for Computing Machinery (ACM)](http://www.acm.org/).


##  Chancellors Research Scholarship (CRS, 2009), Swinburne University 

CRS is the Swinburne University's premier research award.- 



#  Academic and Research Experiences

## **Associate Professor of Statistics**, Menoufia University [October 2020 - To Date]

I am an **Associate Professor of Statistics** in Department of Statistics, Insurance and Mathematics at Faculty of Commerce, Menoufia University, Egypt. 
Before that, I worked in the same department as an **Assistant Professor of Statistics** from September 2015 to September 2020, and also as a **Teaching Assistant** from May 2007 to April 2010. The courses I have been teaching for undergraduate include:

- Pure Mathematics		
- Applied Mathematics		
- Principles of Statistics 
- Applied Statistics 
- Quantitative Analysis

Courses I have been teaching for Postgraduate include: 

- Advanced Statistics	
- Theory of Statistics
- Mathematics for Statisticians	
- Demography
- Time Series Analysis


## **Adjunct Research Fellow**, Swinburne University of Technology [March 2014 - February 2017] 

I have worked as an **Adjunct Research Fellow** at Faculty of Science, Engineering, and Technology (FSET), Swinburne University of Technology, Australia during March 2014 - February 2017.

## **PhD Candidate and Tutor**, Swinburne University of Technology [April 2010 - January 2014]  

The main courses I have been tutoring include: 

- HMS215 Engineering Mathematics 3C.
- HMS214 Engineering Mathematics 4B.
- HMS211M Engineering Mathematics 3M.
- HES5102/HES5103 Research Project.


## **Statistician**, IDSC, Egyptian Cabinet, Egypt [October 2006 - April 2007]

After my graduation I directly worked as a **Statistician** in Data Quality Unit at Information and Decision Support Center (IDSC), Egyptian Cabinet, Egypt.
     
     
     
     


# Consultation Experiences

I deliver statistical consultations for many clients such as regional projects, companies, and postgraduate students in different fields including information technology, social and educational sciences, linguistics, and medicine. 


## [Measurement and Evaluation Project, Menoufia University](http://mu.menofia.edu.eg/CenEv/CedoHome/ar) [November 2018 - To Date]

This project is funded by the Ministry of Higher Education, and I am the **Head of Statistics and Opinion Polls Unit** in the project at Faculty of Commerce.


## [Arab Knowledg Indicator (AKI)](http://www.knowledge4all.com/en/Arab-World-Knowledge-Index/2015) [August 2015 - November 2015]

This Project of Arab Knowledg Indicator (AKI)-2015 was funded by United Nations Development Programme (UNDP) and  Mohammed Bin Rashid Al Maktoum Knowledge Foundation. My participation in this project was writing a technical paper titled _On Constructing Composite Indicators: Background Paper_, giving all the required background to construct the Arab Knowledge Indicator.


## [Planning [in] Justice Project](http://www.tadamun.co/introduction-planing-justice-project/?lang=en#.XRWPdrDVLIU) [June 2015 - December 2015]

This Project is a joint effort between Takween Integrated Community Development (in Egypt) and the American University in Washington, D.C. 
I was the statistician of this project, proposing and constructing composite indicators to measure multidimensional spatial inequalities.

## Consultations for Postgraduate Students

I have been working as a statistical consultant for many PhD studies especially that include surveys as a main component of the thesis. Examples of these PhD studies include:

- Politeness and Requests in Contemporary Arabic: A Case Study of Saudi Women (PhD in Linguistics).
- Analysis of Economic Policies of Foreign Direct Investment (FDI): A case study of Libya (PhD in Economics).
- Adaptive IT Capability and its Impact on the Competitiveness of Firms: A Dynamic Capability Perspective (PhD in Computer Science).
- Hospitalised Children: Reactions of Siblings (PhD in Nursing).

  