---
date: "2018-09-09T00:00:00Z"
draft: false
lastmod: "2018-09-09T00:00:00Z"
linktitle: Consultation Experiences
menu:
  example:
    name: Consultations
    weight: 5
summary: 
title: Consultation Experiences
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 3
weight: 5
type: docs
---


I deliver statistical consultations for many clients such as regional projects, companies, and postgraduate students in different fields including information technology, social and educational sciences, linguistics, and medicine. 


# [Measurement and Evaluation Project](http://mu.menofia.edu.eg/CenEv/CedoHome/ar)

**@ Menoufia University [November 2018 - To Date]**

This project is funded by the Ministry of Higher Education, and I am the **Head of Statistics and Opinion Polls Unit** in the project at Faculty of Commerce.


# [Arab Knowledg Indicator (AKI)](http://www.knowledge4all.com/en/Arab-World-Knowledge-Index/2015)

**@ UNDP [August 2015 - November 2015]**

This Project of Arab Knowledg Indicator (AKI)-2015 was funded by United Nations Development Programme (UNDP) and  Mohammed Bin Rashid Al Maktoum Knowledge Foundation. My participation in this project was writing a technical paper titled _On Constructing Composite Indicators: Background Paper_, giving all the required background to construct the Arab Knowledge Indicator.


# [Planning [in] Justice Project](http://www.tadamun.co/introduction-planing-justice-project/?lang=en#.XRWPdrDVLIU)

**@ Takween [June 2015 - December 2015]**

This Project is a joint effort between Takween Integrated Community Development (in Egypt) and the American University in Washington, D.C. 
I was the statistician of this project, proposing and constructing composite indicators to measure multidimensional spatial inequalities.

# Consultations for Postgraduate Students

I have been working as a statistical consultant for many PhD studies especially that include surveys as a main component of the thesis. Examples of these PhD studies include:

- Politeness and Requests in Contemporary Arabic: A Case Study of Saudi Women (PhD in Linguistics).
- Analysis of Economic Policies of Foreign Direct Investment (FDI): A case study of Libya (PhD in Economics).
- Adaptive IT Capability and its Impact on the Competitiveness of Firms: A Dynamic Capability Perspective (PhD in Computer Science).
- Hospitalised Children: Reactions of Siblings (PhD in Nursing).

  