---
date: "2018-09-09T00:00:00Z"
draft: false
lastmod: "2018-09-09T00:00:00Z"
linktitle: General Background
menu:
  example:
    name: Background
    weight: 1
summary: 
title: General Background
toc: false
type: docs
weight: 1
---

I am a **Professor of Applied Statistics** (since January 2026) at <a href = "http://www.menofia.edu.eg/Home/en">Faculty of Commerce, Menoufia University, Egypt</a>. Before that, I worked as an Associate Professor of Applied Statistics from October 2020 to January 2026, and an Assistant Professor of Statistics from September 2015 to October 2020 at <a href = "http://www.menofia.edu.eg/Home/en">Faculty of Commerce, Menoufia University, Egypt</a>. In addition, I worked as a Tutor for Statistics and Mathematics from February 2012 to June 2014 at <a href = "http://www.swin.edu.au/">Faculty of Science, Engineering and Technology, Swinburne University of Technology, Australia</a>. Moreover, I worked as a Teaching Assistant for Statistics and Mathematics from May 2007 to April 2010 at <a href = "http://www.menofia.edu.eg/Home/en">Faculty of Commerce, Menoufia University, Egypt</a>. I was awarded my PhD from <a href = "http://www.swin.edu.au/">Faculty of Science, Engineering and Technology, Swinburne University of Technology, Australia</a> (in January 2014), and I was awarded my MSc in Statistics (with excellent degree in October 2009) and BSc in Statistics and Social Science Computing (with excellent degree in June 2006) from <a href = "http://www.feps.eun.eg/">Faculty of Economics and Political Science (FEPS), Cairo University</a>, Egypt.

My research work is mainly in time series analysis and forecasting methods. In my *Master study*, I  proposed a Bayesian inference for multiplicative seasonal ARMA models by implementing MCMC Gibbs sampling algorithm. In addition in my *PhD study*, I continued my work in time series analysis but mostly in the real application of time series forecasting. In particular, I was working on proposing an automated statistical approach to forecasting Quality attributes of software systems. These Quality attributes include performance, reliability, and availability. This forecasting approach is mainly based on linear and non-linear time series models and wavelet analysis. Currently, I am mainly working on modeling *multiple seasonalities* aiming to propose a new efficient forecasting method that can be effectively applied in different research fields such as finance, economics and software engineering. 

I deliver statistical consultations for many clients such as regional projects, companies, and postgraduate students in different fields including information technology, social and educational sciences, linguistics, and medicine that require the statistical analysis and data mining as a main component in their work. 
