---
title: ' الرقم القياسي لأسعار المساكن: تجارب دولية ومنهجية للتطبيق في مصر' 
author: Ayman Amin
date: '2018-05-13'
categories:
  - Composite Indicators
  - مؤشرات مصرية
tags:
  - Linear Regression
  - OLS
summary: الرقم القياسي لأسعار المساكن عبارة عن مؤشر مركب يقيس متوسط تغيرات أسعار مبيعات المساكن والعقارات المختلفة التي تم تداولها في السوق خلال فترة معينة
slug: house-price-index
---
<style>
h1, h2, h3, h4, h5, h6 {
  direction: rtl;
}
p {
  direction: rtl;
}
</style>


<p align="right">
منذ عشر سنوات مع بداية 2008، كنت أفكر في بناء مؤشر لقياس أسعار المساكن والعقارات في مصر، ووقتها فعلاً قرأت في الموضوع وحاولت فيه لأكثر من سنة - مع مساعدة بعض الباحثين الأكثر مني خبرة - لأقتراح "رقم قياسي لأسعار المساكن" وهو عبارة عن "مؤشر مركب يقيس متوسط تغيرات أسعار مبيعات المساكن والعقارات المختلفة التي تم تداولها في السوق خلال فترة معينة، وهذه الفترة قد تكون شهر أو ربع سنة أو تزيد لسنة. كما أنه يعكس الخصائص المختلفة لهذه المساكن والعقارات والتي تحدد أسعارها في السوق"، ولكن الحقيقة لم أنجح في هذا لأنه عمل يحتاج إلي فريق متكامل متعدد الخبرات، ووقتها أنشغلت في الدراسات العليا وتركت الموضوع.  
</p>

<p align="right"> 
وفعلاً مازلت أجد أن هذا الرقم القياسي لأسعار المساكن مهم جداً للبلد ككل، وخاصةً لكل من يهتم بالتخطيط العمراني أو سوق العقارات واستثماراتها وبشكل خاص في المدن الجديدة.
أظن أن الباحثين المهتمين بالتخطيط العمراني وعلاقته بسوق العقارات واستثماراتها في مصر يمكن لهم أن يقوموا بهذا المشروع بالتعاون مع الحكومة ومن خلال التقديم علي دعم مالي من منظمات دولية ذات إهتمام بالموضوع.  
</p>


<p align="right"> 
كل بحثي في موضوع الرقم القياسي لأسعار المساكن ومنهجية تطبيقه في مصر وضعته في تقرير متكامل، لعله يجد من يستفيد به ويبني عليه. بسبب مرور قرابة عشر سنوات علي فكرته فهو بحاجة للتحديث. يمكن تحميل التقرير من <a href = "https://www.researchgate.net/publication/322452580_House_Price_Index_International_Experiences_and_A_Methodology_for_Application_in_Egypt_In_Arabic"> هنا</a> .
</p>

