---
title: ' المشكلة السكانية في مصر' 
author: Ayman Amin
date: '2018-01-18'
categories:
  - Composite Indicators
  - مؤشرات مصرية
tags:
  - Linear Regression
summary: المشكلة السكانية في مصر  بين نتائج المسح السكاني الصحي في 2014 ونتائج تعداد السكان 2017
slug: population-problem-inEgypt
---
<style type="text/css">
h1.title {
   direction: rtl;
}
h1, h2, h3, h4, h5, h6 {
  direction: rtl;
}
p {
  direction: rtl;
}
</style>



<p align="right">
بمناسبة مبادرة "شباب جامعات مصر" التي تدشنها الآن وزارة الصحة والسكان للحد من الزيادة السكانية، أذكر عندما كنت حديث التخرج عملت كباحث في وحدة متابعة وتقييم الخطة الإستراتيجية للسكان في مصر، ووقتها كنت مجرد باحث مساعد لمجموعة من خبراء السكان (من بينهم الدكتورة فاطمة الزهراء جيل)، وقمنا بدراسة مهمة عن تقدير المستهدفات الكمية لأهم مؤشرات المتابعة والتقييم للبرنامج السكاني في مصر، وبناءاً علي نتائج هذه الدراسة قدمت ورقة بحثية في "المؤتمر الإقليمي الأول: مواجهة المشكلة السكانية في صعيد مصر"، والذي عُقد في جامعة أسيوط 1-2 أبريل 2009. ما ذكَرني تحديداً بهذه الورقة، هو أني كنت أرتب المجلدات القديمة في مكتبتي فوجدت كتاب المؤتمر، ففتحته وبدأت أقرأ هذه الورقة البحثية التي مر علي ما بها من نتائج وإسقاطات سكانية أكثر من 10 سنوات. الحقيقة صُدمت، لأن كل ما بها من إسقاطات سكانية أبعد ما يكون عن الواقع الحالي. فعلي سبيل المثال في هذه الورقة كان من المتوقع إذا استمر وضع الإنجاب علي ما هو عليه من معدل انخفاض مشاهد خلال الفترة (1995- 2005 )، فهذا سوف يؤدى إلى الوصول إلى معدل إنجاب كلِّى قدره (2.5 طفل لكل سيدة عام 2015). وسبب الصدمة أن نتائج المسح السكاني الصحي في 2014 أفادت أن معدل الإنجاب الكلِّى بلغ تقريبا 3.5 طفل لكل سيدة مقارنةً بـتقريبا 3.0 طفل لكل سيدة في عام 2008. </p>

<p align="right"> 
أظن أن المشكلة السكانية في مصر فعلاً تحتاج طريقة تفكيرجديدة ومختلفة عن السابق حتي نصل لنتائج حقيقية في إتجاه تحسين الوضع السكاني في مصر، وبناءاً علي نتائج تعداد السكان 2017 يجب ان يكون هناك إتجاه قوي نحو تغيير أدواتنا في التعامل مع هذه المشكلة الحقيقية في مصر.</p>


<p align="right"> الورقة مرفقة لمن يهتم بالقضية السكانية والبرنامج السكاني في مصر، كذلك تجدر الإشارة أن هذه الورقة يمكن تحديثها في جانبين مهمين: الجانب الأول هو دراسة الوضع السكاني الراهن ومحاولة معرفة الأسباب الحقيقية للتغير غير المتوقع في إتجاهات الانجاب في أخر عشر سنوات؛ أم الجانب الثاني فهو إستخدام بيانات المسح السكاني الصحي 2014 وبيانات تعداد السكان 2017 لوضع سيناريوهات مختلفة لعمل تقديرات سكانية حتي عام 2050 لإستخدامها في الجوانب المختلفة لخطة التنمية المستدامة في مصر. للتحديث. يمكن تحميل الورقة كاملة من <a href = "https://www.researchgate.net/publication/322448040_Estimating_the_quantitative_values_for_the_monitoring_and_evaluation_indicators_of_the_population_problem_2005-2017_In_Arabic"> هنا</a> .
</p>
